updates to ci to stop bugging about release_notes on shipit

diff --git a/ci/scripts/shipit b/ci/scripts/shipit
--- a/ci/scripts/shipit
+++ b/ci/scripts/shipit
@@ -24,10 +24,11 @@ if [[ -z ${VERSION} ]]; then
   exit 2
 fi
 
-if [[ ! -f ${REPO_ROOT}/ci/release_notes.md ]]; then
-  echo >&2 "ci/release_notes.md not found.  Did you forget to write them?"
-  exit 1
-fi
+## do we want to do github releases?
+#if [[ ! -f ${REPO_ROOT}/ci/release_notes.md ]]; then
+#  echo >&2 "ci/release_notes.md not found.  Did you forget to write them?"
+#  exit 1
+#fi
 
 ###############################################################
 
@@ -55,7 +56,8 @@ mv website-repo.tar.gz ${REPO_ROOT}/src/website/.
 mkdir -p ${RELEASE_ROOT}/artifacts
 echo "v${VERSION}"                         > ${RELEASE_ROOT}/tag
 echo "${RELEASE_NAME} v${VERSION}"         > ${RELEASE_ROOT}/name
-mv ${REPO_ROOT}/ci/release_notes.md          ${RELEASE_ROOT}/notes.md
+#mv ${REPO_ROOT}/ci/release_notes.md          ${RELEASE_ROOT}/notes.md
+echo "Release ${RELEASE_NAME} v${VERSION}" > ${RELEASE_ROOT}/notes.md
 cp ${REPO_ROOT}/releases/${RELEASE_NAME2}/${RELEASE_NAME2}-${VERSION}.tgz  ${RELEASE_ROOT}/artifacts
 
 cat > ${RELEASE_ROOT}/notification <<EOF
@@ -64,18 +66,18 @@ EOF
 
 
 # GIT!
-if [[ -z $(git config --global user.email) ]]; then
-  git config --global user.email "ben.jackson@oakton.com.au"
-fi
-if [[ -z $(git config --global user.name) ]]; then
-  git config --global user.name "Ben Jackson"
-fi
+#if [[ -z $(git config --global user.email) ]]; then
+#  git config --global user.email "ben.jackson@oakton.com.au"
+#fi
+#if [[ -z $(git config --global user.name) ]]; then
+#  git config --global user.name "Ben Jackson"
+#fi
 
-(cd ${REPO_ROOT}
- git merge --no-edit ${BRANCH}
- git add -A
- git status
- git commit -m "release v${VERSION}")
+#(cd ${REPO_ROOT}
+# git merge --no-edit ${BRANCH}
+# git add -A
+# git status
+# git commit -m "release v${VERSION}")
 
 # so that future steps in the pipeline can push our changes
 cp -a ${REPO_ROOT} ${REPO_OUT}
