updates to ci to stop bugging about release_notes on shipit

diff --git a/ci/scripts/shipit b/ci/scripts/shipit
--- a/ci/scripts/shipit
+++ b/ci/scripts/shipit
@@ -25,7 +25,7 @@ if [[ -z ${VERSION} ]]; then
 fi
 
 if [[ ! -f ${REPO_ROOT}/ci/release_notes.md ]]; then
-  echo >&2 "ci/release_notes.md not found.  Did you forget to write them? I'll do it for you this time"
+  echo >&2 "ci/release_notes.md not found.  Did you forget to write them?"
   exit 1
 fi
 
@@ -55,7 +55,7 @@ mv website-repo.tar.gz ${REPO_ROOT}/src/website/.
 mkdir -p ${RELEASE_ROOT}/artifacts
 echo "v${VERSION}"                         > ${RELEASE_ROOT}/tag
 echo "${RELEASE_NAME} v${VERSION}"         > ${RELEASE_ROOT}/name
-cp ${REPO_ROOT}/ci/release_notes.md          ${RELEASE_ROOT}/notes.md
+mv ${REPO_ROOT}/ci/release_notes.md          ${RELEASE_ROOT}/notes.md
 cp ${REPO_ROOT}/releases/${RELEASE_NAME2}/${RELEASE_NAME2}-${VERSION}.tgz  ${RELEASE_ROOT}/artifacts
 
 cat > ${RELEASE_ROOT}/notification <<EOF
